# Generated by Django 5.0.3 on 2024-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0002_product_productcolorimage_productsize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolorimage",
            name="image",
            field=models.ImageField(upload_to="images/product"),
        ),
    ]
