# Generated by Django 5.0.3 on 2024-04-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0012_categoryoffer_new_price_categoryoffer_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="per_expiry_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
