# Generated by Django 5.0.3 on 2024-05-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0018_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
