# Generated by Django 5.0.3 on 2024-05-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0019_brand_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryoffer",
            name="offer_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
