# Generated by Django 5.0.3 on 2024-05-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0020_categoryoffer_offer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoryoffer",
            name="new_price",
        ),
        migrations.RemoveField(
            model_name="categoryoffer",
            name="old_price",
        ),
        migrations.AddField(
            model_name="categoryoffer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
