# Generated by Django 5.0.3 on 2024-05-16 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0021_remove_categoryoffer_new_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("banner_image", models.ImageField(upload_to="images/banner")),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=200)),
                ("is_listed", models.BooleanField(default=True)),
                (
                    "product_color_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banner",
                        to="admin_app.productcolorimage",
                    ),
                ),
            ],
        ),
    ]
