# Generated by Django 5.0.3 on 2024-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_delete_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="referral_count",
            field=models.IntegerField(default=0),
        ),
    ]
