# Generated by Django 5.0.3 on 2024-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customer_referral_code_customer_referral_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="referred_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
