# Generated by Django 5.0.3 on 2024-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_referred_code_customer_referred_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
