# Generated by Django 5.0.3 on 2024-04-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0008_alter_orderitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart_app.cartitem"
            ),
        ),
    ]
