# Generated by Django 5.0.3 on 2024-04-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0022_cartitem_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("paid_at", models.DateTimeField(null=True)),
                ("pending", models.BooleanField(default=True)),
                ("failed", models.BooleanField(default=False)),
                ("success", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cart_app.payment",
            ),
        ),
    ]
