# Generated by Django 5.0.3 on 2024-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0023_payment_remove_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounted_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
