# Generated by Django 5.0.3 on 2024-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0024_alter_order_discounted_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Placed", "Order Placed"),
                    ("Pending", "Pending"),
                    ("Shipped", "Shipped"),
                    ("Out for Delivery", "Out for Delivery"),
                    ("Delivered", "Delivered"),
                    ("Returned", "Returned"),
                    ("Refunded", "Refunded"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
