# Generated by Django 5.0.3 on 2024-04-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0026_orderitem_cancel_product_orderitem_request_return_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="cancel_product",
        ),
    ]
