# Generated by Django 5.0.3 on 2024-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0030_alter_wallet_transaction_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet_transaction",
            name="referral_deposit",
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
