# Generated by Django 5.0.3 on 2024-05-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0031_wallet_transaction_referral_deposit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet_transaction",
            name="referral_deposit",
        ),
        migrations.AddField(
            model_name="wallet",
            name="referral_deposit",
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
