# Generated by Django 5.0.3 on 2024-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0032_remove_wallet_transaction_referral_deposit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Pending", "Pending"),
                    ("Payment Failed", "Payment Failed"),
                    ("Payment Successful", "Payment Successful"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="each_price",
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
