# Generated by Django 5.0.3 on 2024-05-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0021_remove_categoryoffer_new_price_and_more"),
        ("cart_app", "0033_order_status_orderitem_each_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_order",
                to="admin_app.productcolorimage",
            ),
        ),
    ]
