# Generated by Django 5.0.3 on 2024-05-25 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0022_banner"),
        ("cart_app", "0037_alter_order_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_cart",
                to="admin_app.productcolorimage",
            ),
        ),
    ]
