# Generated by Django 5.0.3 on 2024-05-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0038_alter_cartitem_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Pending", "Pending"),
                    ("Payment Failed", "Payment Failed"),
                    ("Payment Successful", "Payment Successful"),
                    ("Returned", "Returned"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
